"""add_status_to_violations

Revision ID: 3ff917d6f045
Revises: 5c9ccaaf62dd
Create Date: 2025-10-13 20:44:49.686945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff917d6f045'
down_revision: Union[str, None] = '5c9ccaaf62dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violations', sa.Column('status', sa.String(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violations', 'status')
    # ### end Alembic commands ###
