"""add user_id 
to violations table

Revision ID: 5c9ccaaf62dd
Revises: 80d858fdf0b4
Create Date: 2025-10-13 03:54:02.149527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9ccaaf62dd'
down_revision: Union[str, None] = '80d858fdf0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'violations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def upgrade():
   
    op.add_column('violations', sa.Column('user_id', sa.Integer(), nullable=True))

    
    op.execute('UPDATE violations SET user_id = 1')

    op.alter_column('violations', 'user_id', nullable=False)

    
    op.create_foreign_key(
        'fk_violations_user_id_users',
        'violations', 'users',
        ['user_id'], ['id']
    )
