"""add violation table

Revision ID: 80d858fdf0b4
Revises: 9932e75c19ff
Create Date: 2025-10-13 02:32:08.907734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d858fdf0b4'
down_revision: Union[str, None] = '9932e75c19ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('worker_code', sa.Text(), nullable=True),
    sa.Column('violation_types', sa.Text(), nullable=True),
    sa.Column('frame_index', sa.Integer(), nullable=True),
    sa.Column('frame_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot', sa.LargeBinary(), nullable=True),
    sa.Column('inference', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violations')
    # ### end Alembic commands ###
