"""add_stream_ url

Revision ID: bbdd5f3227a5
Revises: 5b861e69385d
Create Date: 2025-10-14 22:13:15.412971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbdd5f3227a5'
down_revision: Union[str, None] = '5b861e69385d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('stream_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'stream_url')
    # ### end Alembic commands ###
